name: Delete aurora and redis stack
on:
  pull_request:
    types: [closed]

jobs:
  delete-feature-branch-infra:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: cdk destroy --all
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'destroy'
          working_dir: 'deployment'
          cdk_args: '--require-approval never'
          actions_comment: true
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-2'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}